name: 💭 Deep thoughts
description: Have a future idea or some random thought you feel can be interesting?
title: "Thoughts: "
body:
  - type: markdown
    attributes:
      value: |
        # Ideas or future plans
        Ideas can come and go and documenting them into issues is a nice way of starting a discussion. 
  - type: textarea
    id: idea-description
    attributes:
      label: Description of the thought
      description: Give us a brief description of what the idea includes and what it could possible solve
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
        Provide any additional information such as links, images, etc that could help people understand the idea and make it easier to join the discussion.